spring.application.name=${SPRING_APPLICATION_NAME:inventory-service}
server.port=${SERVER_PORT:5001}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/inventory_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ardp28}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root28}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

logging.level.root=INFO
logging.level.org.springframework.web=INFO